name: uri_online_judge
description: URI Online Judge

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #path_provider: ^1.6.18
  #url_launcher: ^5.7.2
  flutter_launcher_icons: ^0.8.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/icon_uri.png"


  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/